# Generated by Django 5.2.10 on 2026-01-30 16:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500, verbose_name='Domanda')),
                ('answer', models.TextField(verbose_name='Risposta')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', models.TextField(verbose_name='Contenuto')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_published', models.BooleanField(default=True, verbose_name='Pubblicata')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Mostra nel menu')),
                ('menu_order', models.PositiveIntegerField(default=0, verbose_name='Ordine menu')),
            ],
            options={
                'verbose_name': 'Pagina',
                'verbose_name_plural': 'Pagine',
                'ordering': ['menu_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Villa Luxury', max_length=200, verbose_name='Nome sito')),
                ('site_description', models.TextField(blank=True, verbose_name='Descrizione sito')),
                ('site_keywords', models.CharField(blank=True, max_length=500, verbose_name='Keywords SEO')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefono')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('address', models.TextField(blank=True, verbose_name='Indirizzo')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('check_in_time', models.TimeField(default='15:00', verbose_name='Orario check-in')),
                ('check_out_time', models.TimeField(default='10:00', verbose_name='Orario check-out')),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Privacy Policy')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='Termini e Condizioni')),
            ],
            options={
                'verbose_name': 'Impostazioni sito',
                'verbose_name_plural': 'Impostazioni sito',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(max_length=200, verbose_name='Nome ospite')),
                ('guest_country', models.CharField(blank=True, max_length=100, verbose_name='Paese')),
                ('content', models.TextField(verbose_name='Testimonianza')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Valutazione')),
                ('stay_date', models.DateField(blank=True, null=True, verbose_name='Data soggiorno')),
                ('is_featured', models.BooleanField(default=False, verbose_name='In evidenza')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Testimonianza',
                'verbose_name_plural': 'Testimonianze',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
