# Generated by Django 5.2.10 on 2026-01-30 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('payment_type', models.CharField(choices=[('DEPOSIT', 'Acconto'), ('BALANCE', 'Saldo'), ('FULL', 'Pagamento completo'), ('REFUND', 'Rimborso')], default='DEPOSIT', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('PROCESSING', 'In elaborazione'), ('COMPLETED', 'Completato'), ('FAILED', 'Fallito'), ('REFUNDED', 'Rimborsato'), ('CANCELLED', 'Cancellato')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('stripe_checkout_session_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Stripe Checkout Session ID')),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Stripe Payment Intent ID')),
                ('stripe_charge_id', models.CharField(blank=True, max_length=200, verbose_name='Stripe Charge ID')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email cliente')),
                ('receipt_url', models.URLField(blank=True, verbose_name='URL ricevuta')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completato il')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fallito il')),
                ('failure_reason', models.TextField(blank=True, verbose_name='Motivo fallimento')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='booking.booking', verbose_name='Prenotazione')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamenti',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo evento')),
                ('event_data', models.JSONField(verbose_name='Dati evento')),
                ('processed', models.BooleanField(default=False, verbose_name='Processato')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processato il')),
                ('error_message', models.TextField(blank=True, verbose_name='Errore')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ricevuto il')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='Pagamento')),
            ],
            options={
                'verbose_name': 'Log pagamento',
                'verbose_name_plural': 'Log pagamenti',
                'ordering': ['-created_at'],
            },
        ),
    ]
