# Generated by Django 5.2.10 on 2026-01-30 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('villa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Numero prenotazione')),
                ('guest_first_name', models.CharField(max_length=100, verbose_name='Nome')),
                ('guest_last_name', models.CharField(max_length=100, verbose_name='Cognome')),
                ('guest_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('guest_phone', models.CharField(max_length=30, verbose_name='Telefono')),
                ('guest_country', models.CharField(blank=True, max_length=100, verbose_name='Paese')),
                ('check_in', models.DateField(verbose_name='Check-in')),
                ('check_out', models.DateField(verbose_name='Check-out')),
                ('num_guests', models.PositiveIntegerField(default=1, verbose_name='Numero ospiti')),
                ('nights', models.PositiveIntegerField(default=1, verbose_name='Notti')),
                ('price_per_night_avg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prezzo medio/notte')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotale')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo pulizie')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Totale')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Acconto')),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo dovuto')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Valuta')),
                ('status', models.CharField(choices=[('PENDING', 'In attesa'), ('CONFIRMED', 'Confermata'), ('CANCELLED', 'Cancellata'), ('COMPLETED', 'Completata'), ('NO_SHOW', 'No show')], default='PENDING', max_length=20, verbose_name='Stato')),
                ('payment_status', models.CharField(choices=[('PENDING', 'In attesa'), ('DEPOSIT_PAID', 'Acconto pagato'), ('FULLY_PAID', 'Pagato totalmente'), ('REFUNDED', 'Rimborsato'), ('PARTIAL_REFUND', 'Parzialmente rimborsato')], default='PENDING', max_length=20, verbose_name='Stato pagamento')),
                ('guest_notes', models.TextField(blank=True, verbose_name='Note ospite')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Note admin')),
                ('arrival_time', models.TimeField(blank=True, null=True, verbose_name='Orario arrivo previsto')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confermata il')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancellata il')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name='Motivo cancellazione')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='villa.bookableunit', verbose_name='Unità')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Utente')),
            ],
            options={
                'verbose_name': 'Prenotazione',
                'verbose_name_plural': 'Prenotazioni',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPriceDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('season_name', models.CharField(blank=True, max_length=100, verbose_name='Stagione')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_details', to='booking.booking', verbose_name='Prenotazione')),
            ],
            options={
                'verbose_name': 'Dettaglio prezzo',
                'verbose_name_plural': 'Dettagli prezzo',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Data')),
                ('reason', models.CharField(choices=[('BOOKING', 'Prenotazione'), ('MAINTENANCE', 'Manutenzione'), ('OWNER', 'Uso proprietario'), ('OTHER', 'Altro')], default='BOOKING', max_length=20, verbose_name='Motivo')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Nota')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='villa.bookableunit', verbose_name='Unità')),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='booking.booking', verbose_name='Prenotazione')),
            ],
            options={
                'verbose_name': 'Data bloccata',
                'verbose_name_plural': 'Date bloccate',
                'ordering': ['date'],
                'unique_together': {('unit', 'date')},
            },
        ),
    ]
