# Generated by Django 5.2.10 on 2026-01-30 16:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('icon', models.CharField(blank=True, help_text='Classe icona (es: heroicons)', max_length=50, verbose_name='Icona')),
                ('category', models.CharField(choices=[('COMFORT', 'Comfort'), ('OUTDOOR', 'Esterni'), ('KITCHEN', 'Cucina'), ('SERVICES', 'Servizi'), ('ENTERTAINMENT', 'Intrattenimento'), ('SAFETY', 'Sicurezza')], default='COMFORT', max_length=20, verbose_name='Categoria')),
                ('is_highlighted', models.BooleanField(default=False, verbose_name='In evidenza')),
            ],
            options={
                'verbose_name': 'Amenity',
                'verbose_name_plural': 'Amenities',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BookableUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('unit_type', models.CharField(choices=[('FULL', 'Intera Villa'), ('APT', 'Appartamento'), ('ROOM', 'Camera')], default='FULL', max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('description_short', models.TextField(blank=True, max_length=300, verbose_name='Descrizione breve')),
                ('max_guests', models.PositiveIntegerField(default=2, verbose_name='Ospiti max')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='Camere')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='Bagni')),
                ('beds_description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione letti')),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Prezzo per notte in bassa stagione', max_digits=10, verbose_name='Prezzo base/notte')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo pulizie')),
                ('min_nights', models.PositiveIntegerField(default=2, verbose_name='Notti minime')),
                ('max_nights', models.PositiveIntegerField(default=30, verbose_name='Notti massime')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='villa/units/', verbose_name='Immagine principale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
            ],
            options={
                'verbose_name': 'Unità prenotabile',
                'verbose_name_plural': 'Unità prenotabili',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('tagline', models.CharField(blank=True, max_length=300, verbose_name='Tagline')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('description_short', models.TextField(blank=True, max_length=500, verbose_name='Descrizione breve')),
                ('address', models.TextField(verbose_name='Indirizzo')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('postal_code', models.CharField(max_length=10, verbose_name='CAP')),
                ('country', models.CharField(default='Italia', max_length=100, verbose_name='Paese')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitudine')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitudine')),
                ('total_guests', models.PositiveIntegerField(default=10, verbose_name='Ospiti totali')),
                ('total_bedrooms', models.PositiveIntegerField(default=5, verbose_name='Camere totali')),
                ('total_bathrooms', models.PositiveIntegerField(default=5, verbose_name='Bagni totali')),
                ('total_sqm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Metri quadri')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='villa/hero/', verbose_name='Immagine hero')),
                ('hero_video_url', models.URLField(blank=True, verbose_name='URL video hero')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='Meta title')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='Meta description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attiva')),
            ],
            options={
                'verbose_name': 'Villa',
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.CreateModel(
            name='SeasonPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome stagione')),
                ('start_date', models.DateField(verbose_name='Data inizio')),
                ('end_date', models.DateField(verbose_name='Data fine')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo/notte')),
                ('min_nights', models.PositiveIntegerField(blank=True, help_text="Sovrascrive il minimo dell'unità per questa stagione", null=True, verbose_name='Notti minime')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_prices', to='villa.bookableunit', verbose_name='Unità')),
            ],
            options={
                'verbose_name': 'Prezzo stagionale',
                'verbose_name_plural': 'Prezzi stagionali',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aggiornato il')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Immagine')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alt text')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Didascalia')),
                ('is_hero', models.BooleanField(default=False, verbose_name='Immagine hero')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Ordine')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='villa.bookableunit', verbose_name='Unità')),
                ('villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='villa.villa', verbose_name='Villa')),
            ],
            options={
                'verbose_name': 'Immagine galleria',
                'verbose_name_plural': 'Immagini galleria',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookableunit',
            name='villa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='villa.villa', verbose_name='Villa'),
        ),
        migrations.CreateModel(
            name='UnitAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.amenity')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_amenities', to='villa.bookableunit')),
            ],
            options={
                'verbose_name': 'Amenity unità',
                'verbose_name_plural': 'Amenities unità',
                'unique_together': {('unit', 'amenity')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='bookableunit',
            unique_together={('villa', 'slug')},
        ),
        migrations.CreateModel(
            name='VillaAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Descrizione')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='villa.amenity')),
                ('villa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villa_amenities', to='villa.villa')),
            ],
            options={
                'verbose_name': 'Amenity villa',
                'verbose_name_plural': 'Amenities villa',
                'unique_together': {('villa', 'amenity')},
            },
        ),
    ]
